apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-database-backup
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "azurefile"
  resources:
    requests:
      storage: {{ .Values.databasebackup.storage }}