apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "theglobetrotters.postgres.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "20"
type: Opaque
data:
  password: |-
        {{ .Values.postgres.password | .Files.Get | trimSuffix "\n" | b64enc }}