apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "theglobetrotters.postgres.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "25"
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    {{- include "theglobetrotters.postgres.selectorLabels" . | nindent 4 }}
