apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails
  labels:
    {{- include "theglobetrotters.rails.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "theglobetrotters.rails.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/postgres_secret: {{ include (print $.Template.BasePath "/20_postgres_secret.yaml") . | sha256sum }}
        checksum/rails_secret: {{ include (print $.Template.BasePath "/30_rails_secret.yaml") . | sha256sum }}
        force_recreate: {{ .Release.Revision | quote }}
      labels:
        {{- include "theglobetrotters.rails.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "theglobetrotters.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: rails
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.rails }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: rails-secret
                key: master_key
          - name: DOCKER_POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password
          - name: RAILS_ENV
            value: production
          - name: RAILS_LOG_TO_STDOUT
            value: '1'
          - name: RAILS_HOST
            value: {{ .Values.app.hostname }}
          - name: DOCKER_POSTGRES_HOST
            value: postgres
          - name: DOCKER_POSTGRES_SSL
            value: allow
          - name: DOCKER_POSTGRES_USER
            value: postgres
          resources:
            {{- toYaml .Values.resources.rails | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
