apiVersion: v1
kind: Service
metadata:
  name: rails
  labels:
    {{- include "theglobetrotters.rails.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    {{- include "theglobetrotters.rails.selectorLabels" . | nindent 4 }}
