name: Deployment

concurrency: production

on:
  push:
    branches:
      - release
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # get 50 commits (useful for sentry)
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build docker images
        run: bundle exec rake azure:docker_build
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          RAKE_WITHOUT_DEPENDENCIES: true
      - name: Validate build
        run: bundle exec rake docker-compose:rake_build_validate
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          RAKE_WITHOUT_DEPENDENCIES: true
      - name: Publish docker images
        run: bundle exec rake azure:docker_setup
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          RAKE_WITHOUT_DEPENDENCIES: true
      - name: Publish static assets
        run: bundle exec rake azure:asset_setup
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          RAKE_WITHOUT_DEPENDENCIES: true
      - name: Update AKS
        run: bundle exec rake aks:deploy
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          RAKE_WITHOUT_DEPENDENCIES: true
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
